In [1]:
import numpy as np

In [3]:
np.array([range(i, i+3) for i in[2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [4]:
np.random.random((3,3))

array([[0.50976906, 0.72980911, 0.66444409],
       [0.99561284, 0.26610353, 0.55536632],
       [0.38816492, 0.0436095 , 0.24916106]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
left, right = np.hsplit(grid, [1])
print(left)
print(right)


[[1]
 [4]
 [7]]
[[2 3]
 [5 6]
 [8 9]]


In [17]:
x = np.array([1,3,5])
grid = np.array([[2,4,6],
                [3,2,1]])
np.vstack([x, grid])

array([[1, 3, 5],
       [2, 4, 6],
       [3, 2, 1]])

In [18]:
x = np.array([[1,3,5],
             [7,9,5]])
grid = np.array([[2,4,6],
                [3,2,1]])
np.concatenate([x, grid], axis = 1)

array([[1, 3, 5, 2, 4, 6],
       [7, 9, 5, 3, 2, 1]])

In [19]:
x = np.array([[1,3,5],
             [7,9,5]])
grid = np.array([[2,4,6],
                [3,2,1]])
np.concatenate([x, grid])

array([[1, 3, 5],
       [7, 9, 5],
       [2, 4, 6],
       [3, 2, 1]])

In [3]:
import numpy as np
x = np.arange(1,10)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [4]:
x = np.arange(20)
np.add.reduce(x)

190

In [5]:
np.add.accumulate(x)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)

In [6]:
np.max(x)

19

In [7]:
np.min(x)

0

In [11]:
%timeit np.sum(x)

14.4 µs ± 3.16 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [12]:
np.argmax(x)

19

In [13]:
a = np.array([1,2,3])
b = np.array([5,5,5])
a+b

array([6, 7, 8])

# 

In [14]:
a+10

array([11, 12, 13])

In [2]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [15]:
rng = np.random.RandomState(50)
x = 10*rng.rand(50)
x

array([4.94601646, 2.28083104, 2.55473924, 3.9632991 , 3.77315098,
       9.9657423 , 4.081972  , 7.71893995, 7.60536688, 3.10009349,
       3.46541205, 3.51764817, 1.45466856, 9.72664685, 9.09178438,
       5.59957104, 3.13590746, 8.88200038, 6.74573066, 3.91087448,
       5.07184124, 5.24103503, 9.28000928, 5.71373069, 6.68337569,
       0.52258691, 3.27057304, 0.56401639, 1.79827694, 9.25933173,
       9.38015223, 7.14092707, 7.32687609, 4.61747676, 9.31329268,
       4.06420243, 6.83205771, 6.49915868, 5.98765179, 2.22039392,
       6.82357169, 8.78056303, 7.96717263, 4.32002248, 9.17878219,
       7.81833678, 7.25750278, 1.24854693, 9.16308449, 3.87710994])

In [7]:
x[:,np.newaxis]

array([[3.74540119],
       [9.50714306],
       [7.31993942],
       [5.98658484],
       [1.5601864 ],
       [1.5599452 ],
       [0.58083612],
       [8.66176146],
       [6.01115012],
       [7.08072578],
       [0.20584494],
       [9.69909852],
       [8.32442641],
       [2.12339111],
       [1.81824967],
       [1.8340451 ],
       [3.04242243],
       [5.24756432],
       [4.31945019],
       [2.9122914 ],
       [6.11852895],
       [1.39493861],
       [2.92144649],
       [3.66361843],
       [4.56069984],
       [7.85175961],
       [1.99673782],
       [5.14234438],
       [5.92414569],
       [0.46450413],
       [6.07544852],
       [1.70524124],
       [0.65051593],
       [9.48885537],
       [9.65632033],
       [8.08397348],
       [3.04613769],
       [0.97672114],
       [6.84233027],
       [4.40152494],
       [1.22038235],
       [4.9517691 ],
       [0.34388521],
       [9.09320402],
       [2.58779982],
       [6.62522284],
       [3.11711076],
       [5.200

In [29]:
rng = np.random.RandomState(10)
x = np.linspace(0, 10, 500)
x

array([ 0.        ,  0.02004008,  0.04008016,  0.06012024,  0.08016032,
        0.1002004 ,  0.12024048,  0.14028056,  0.16032064,  0.18036072,
        0.2004008 ,  0.22044088,  0.24048096,  0.26052104,  0.28056112,
        0.3006012 ,  0.32064128,  0.34068136,  0.36072144,  0.38076152,
        0.4008016 ,  0.42084168,  0.44088176,  0.46092184,  0.48096192,
        0.501002  ,  0.52104208,  0.54108216,  0.56112224,  0.58116232,
        0.6012024 ,  0.62124248,  0.64128257,  0.66132265,  0.68136273,
        0.70140281,  0.72144289,  0.74148297,  0.76152305,  0.78156313,
        0.80160321,  0.82164329,  0.84168337,  0.86172345,  0.88176353,
        0.90180361,  0.92184369,  0.94188377,  0.96192385,  0.98196393,
        1.00200401,  1.02204409,  1.04208417,  1.06212425,  1.08216433,
        1.10220441,  1.12224449,  1.14228457,  1.16232465,  1.18236473,
        1.20240481,  1.22244489,  1.24248497,  1.26252505,  1.28256513,
        1.30260521,  1.32264529,  1.34268537,  1.36272545,  1.38

In [36]:
y = np.cumsum(rng.randn(500, 6), 0)
y

array([[ -1.42088052,  -0.67894677,   0.53388481,   0.7439744 ,
          2.22504964,   0.11718142],
       [ -1.17626599,  -0.8562456 ,   0.12815528,   1.52574959,
          2.57852725,  -0.09009807],
       [ -2.25596338,  -0.97931543,  -0.2628269 ,   2.78092333,
          3.52565333,  -1.11240876],
       ...,
       [ -8.72979163,  28.6357283 ,  -6.47153945, -31.73833975,
        -22.39693309, -19.03301435],
       [ -7.47710577,  28.78718626,  -6.85446881, -32.5207026 ,
        -21.33992551, -17.8296004 ],
       [ -8.47879398,  28.2588222 ,  -7.32700994, -31.55396376,
        -22.00388739, -17.67703864]])